function interfata_dioda(A,T,f,R,vf,tipS,tipD)
set(gcf,'color','w');
imglpf=imread('media_d87_d871a777-3801-49df-b862-b6d5cd438b0c_phpviCszD.png');
grid off;
subplot(2,3,1);
imshow(imglpf);
Titlu=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.25 0.94 0.041 0.04],...
'String',"Dioda");
Rezistenta=uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.19 0.796 0.045 0.03],...
'String',R,...
'Value',R,...
'Callback','R=str2num(get(gco,''String''));interfata_dioda(A,T,f,R,vf,tipS,tipD);calcul_dioda(A,T,f,R,vf,tipS,tipD)');
Amplitudine=uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.1 0.7 0.041 0.03],...
'String',A,...
'Value',A,...
'Callback','A=str2num(get(gco,''String''));interfata_dioda(A,T,f,R,vf,tipS,tipD);calcul_dioda(A,T,f,R,vf,tipS,tipD)');
Amplitt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.1 0.73 0.041 0.03],...
'String',"Amplitudine");
tipSemnal=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.65 0.87 0.05 0.03],...
'String',"Tip Semnal");
tipDioda=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.72 0.87 0.05 0.03],...
'String',"Tip Dioda");
tipSemnalT=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.65 0.80 0.05 0.07],...
'String','DC|SIN|DR|TR',...
'Value',tipS,...
'Callback','tipS=get(gco,''Value'');interfata_dioda(A,T,f,R,vf,tipS,tipD);calcul_dioda(A,T,f,R,vf,tipS,tipD)');
tipDiodaT=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.72 0.80 0.05 0.07],...
'String','Siliciu(1N4001) |Germanium(1N34A)|Ga-Ar(Galiu-Arseniu)-rosu|Ga-Ar-verde|Ga-Ar-albastru',...
'Value',tipD,...
'Callback','tipD=get(gco,''Value'');interfata_dioda(A,T,f,R,vf,tipS,tipD);calcul_dioda(A,T,f,R,vf,tipS,tipD)');
tipSemnal=uicontrol('Style','PopupMenu',...
'Units','normalized',...
'Position',[0.65 0.80 0.05 0.07],...
'String','DC|SIN|DR|TR',...
'Value',tipS,...
'Callback','tipS=get(gco,''Value'');interfata_dioda(A,T,f,R,vf,tipS,tipD);calcul_dioda(A,T,f,R,vf,tipS,tipD)');
end